// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp3BShT5qZ2G07fVTnbtlqMNGOzhbXxr0',
    appId: '1:977501946978:web:4e57058f44489bcdefbd3b',
    messagingSenderId: '977501946978',
    projectId: 'unispend-mwp',
    authDomain: 'unispend-mwp.firebaseapp.com',
    storageBucket: 'unispend-mwp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy23gThqk6Ji_ggTrQkAruqBUnb-XkFEo',
    appId: '1:977501946978:android:42a11661d2262bb6efbd3b',
    messagingSenderId: '977501946978',
    projectId: 'unispend-mwp',
    storageBucket: 'unispend-mwp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG4mH-qxB5qxLjZey8s8VIRs7J5jtLJBw',
    appId: '1:977501946978:ios:b9e2f7832e6d1a05efbd3b',
    messagingSenderId: '977501946978',
    projectId: 'unispend-mwp',
    storageBucket: 'unispend-mwp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG4mH-qxB5qxLjZey8s8VIRs7J5jtLJBw',
    appId: '1:977501946978:ios:b9e2f7832e6d1a05efbd3b',
    messagingSenderId: '977501946978',
    projectId: 'unispend-mwp',
    storageBucket: 'unispend-mwp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp3BShT5qZ2G07fVTnbtlqMNGOzhbXxr0',
    appId: '1:977501946978:web:7d20552da989061cefbd3b',
    messagingSenderId: '977501946978',
    projectId: 'unispend-mwp',
    authDomain: 'unispend-mwp.firebaseapp.com',
    storageBucket: 'unispend-mwp.firebasestorage.app',
  );
}
